theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = true
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal] 
H = "goto_previous_buffer"
L = "goto_next_buffer"
K = "page_cursor_up"
J = "page_cursor_down"
X = ["extend_line_up", "extend_to_line_bounds"]
C-q = ":quit"
A-t = [":sh alacritty --working-directory %sh{dirname %{buffer_name}}"]

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal."space"]
F = "file_picker_in_current_buffer_directory"
w = ":write"
n = ":new"
l = ":fmt"
q = ":buffer-close"
# e = [
#   ':sh rm -f /tmp/unique-file',
#   ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
#   ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
#   ':open %sh{cat /tmp/unique-file}',
#   ':redraw',
# ]
