#!/bin/sh
#####################
# autostart programs
#####################
# start autostart programs at /etc/xdg/autostart
riverctl spawn "dex -a"

# start notification daemon
riverctl spawn mako

# start status bar
killall -q waybar
riverctl spawn waybar

# enable tap to click
riverctl input pointer-1739-30966-Synaptics_TM3096-006 tap enabled

# turn on night light
gammastep -O 4500 &

##########
# keymaps
##########
# media keys
riverctl map normal None XF86AudioRaiseVolume  spawn '~/.local/scripts/volume.sh --up'
riverctl map normal None XF86AudioLowerVolume  spawn '~/.local/scripts/volume.sh --down'
riverctl map normal None XF86AudioMute spawn '~/.local/scripts/volume.sh --mute'
riverctl map normal None XF86MonBrightnessUp spawn '~/.local/scripts/light.sh --up'
riverctl map normal None XF86MonBrightnessDown spawn '~/.local/scripts/light.sh --down'
riverctl map normal None XF86AudioPlay  spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev  spawn 'playerctl previous'
riverctl map normal None XF86AudioNext  spawn 'playerctl next'

# restart river config
riverctl map normal Super r ~/.config/river/init

# reboot
riverctl map normal Super Delete spawn systemctl reboot -i

# shutdown
riverctl map normal Super End spawn systemctl poweroff

# terminal
riverctl map normal Super Return spawn ghostty

# document reader
riverctl map normal Super D spawn zathura

# browser
riverctl map normal Super B spawn firefox

# menu
riverctl map normal Super M spawn wofi

# toggle night light
riverctl map normal Super N spawn 'pkill gammastep || gammastep -O 4500'

# close the focused view
riverctl map normal Super q close

# exit river
riverctl map normal Super Escape exit

# focus the next/previous window in the layout stack
riverctl map normal Super l focus-view next
riverctl map normal Super h focus-view previous

# bump the focused view to the top of the layout stack
riverctl map normal Super t zoom

# decrease/increase the size of window
riverctl map normal Super+Shift h send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Shift l send-layout-cmd rivertile "main-ratio +0.05"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super f toggle-fullscreen

##################################
# options
#################################
# set background color
riverctl background-color 0x0f1419

# Set keyboard repeat rate
riverctl set-repeat 50 300

# floating windows rules
riverctl float-filter-add title Library
riverctl float-filter-add app-di gpartedbin

# Set the default layout generator to be rivertile and start it.
riverctl default-layout rivertile

# Add padding to windows
rivertile -view-padding 2 -outer-padding 2 &

