#!/bin/sh

# start autostart programs
riverctl spawn "dex -a"

# set wallpaper
riverctl spawn ~/.local/scripts/wallpaper.sh

# restart river config
riverctl map normal Super+Shift R spawn ~/.config/river/init

#enable tap to click
riverctl input pointer-1739-30966-Synaptics_TM3096-006 tap enabled

# Media keys
riverctl map normal None XF86AudioRaiseVolume  spawn '~/.local/scripts/volume.sh --up'
riverctl map normal None XF86AudioLowerVolume  spawn '~/.local/scripts/volume.sh --down'
riverctl map normal None XF86AudioMute spawn '~/.local/scripts/volume.sh --mute'
riverctl map normal None XF86MonBrightnessUp spawn '~/.local/scripts/light.sh --up'
riverctl map normal None XF86MonBrightnessDown spawn '~/.local/scripts/light.sh --down'
riverctl map normal None XF86AudioPlay  spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev  spawn 'playerctl previous'
riverctl map normal None XF86AudioNext  spawn 'playerctl next'

# terminal
riverctl map normal Super Return spawn alacritty

# browser
riverctl map normal Super B spawn firefox

# menu
riverctl map normal Super M spawn wofi

# close the focused view
riverctl map normal Super Q close

# exit river
riverctl map normal Super+Shift E exit

# focus the next/previous view in the layout stack
riverctl map normal Super L focus-view next
riverctl map normal Super H focus-view previous

# bump the focused view to the top of the layout stack
riverctl map normal Super T zoom

# decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-ratio +0.05"

# move views
riverctl map normal Super Left move left 100
riverctl map normal Super Down move down 100
riverctl map normal Super Up move up 100
riverctl map normal Super Right move right 100

# resize views
riverctl map normal Super+Shift Left resize horizontal -100
riverctl map normal Super+Shift  Down resize vertical 100
riverctl map normal Super+Shift  Up resize vertical -100
riverctl map normal Super+Shift  Right resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super+Alt Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Alt Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Alt Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Supe+Altr Left  send-layout-cmd rivertile "main-location left"

# Set keyboard repeat rate
riverctl set-repeat 50 300

# floating windows rules
riverctl float-filter-add title Library
riverctl float-filter-add app-di gpartedbin

# Set the default layout generator to be rivertile and start it.
riverctl default-layout rivertile

# Add padding to windows
rivertile -view-padding 2 -outer-padding 5 &
